### ISSUE TITLE
Link Requires Credit Card Details

### ISSUE THREAD

**Issue by abrar39** [claimed-framework/component-library#177]
When creating account using given link, it still requires credit card information.

**Comment by FloRed** [comment]
The same

**Comment by dyh2908** [comment]
The same. Will we get charged

**Comment by yours-anonym** [comment]
I have the same problem

**Comment by Vedant3** [comment]
I am having the same issue regarding credit card

**Comment by romeokienzler** [comment]
Please use the course discussion forum - btw. all learning assets are moved to https://github.com/claimed-framework/education, so if you find an error in the code, please file it [there](https://github.com/claimed-framework/education/issues)
